### ISSUE TITLE
WTF?!!

### ISSUE THREAD

**Issue by Devdutt-Shenoi** [steevjames/Contribute#11]
So, you have basically made this gimmick look like one... Congrats, you have achieved the ultimate potential of SteevMEC :rofl:

**Comment by steevjames** [comment]
@Devdutt-Shenoi Certain phenomenon are incomprehensible to monotonous minds. Contact https://t.justdial.com/Thiruvananthapuram/Mental-Health-Care-Oolampara/0471PX471-X471-140630103046-N3E6_BZDET to have all your problems soved.
